name: Transfer (Pull & Push) DockerHub images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Transfer (Pull & Push) DockerHub images
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
      run: |
           docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY

           while IFS= read -r full_image_name
           do
                raw_image_name=${full_image_name##*/}
                docker pull --platform=linux/arm64 $full_image_name \
                    && docker tag $full_image_name ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/$raw_image_name \
                    && docker push ${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/$raw_image_name
           done < images.txt
